countries/urls.py
from django.conf.urls import url,include
from.import views

app_name = 'countries';

urlpatterns = [
     url(r'^form/$', views.country_list, name="country_list"),
     url(r'^ajaxcall/$', views.Ajaxcall, name="Ajaxcall"),
     url(r'^ajaxcalldistrict/$', views.Ajaxcall_district, name="Ajaxcall_district"),
     url(r'^ajaxcountry/$',views.Ajaxcallcountry,name="Ajaxcallcountry")
]

dropdown/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^countries/',include('countries.urls'))
    
]

countries/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Country(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return '{}'.format(self.name)

class City(models.Model):
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)

    def __str__(self):
         return '{} {}'.format(self.name,self.pk)

class District(models.Model):
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)

    def __str__(self):
        return '{}'.format(self.name)

countries/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Country,City,District
import pdb
import json,ast
# Create your views here.
def country_list(request,template_name="file.html"):

    all_countries = Country.objects.all()


    return render(request,template_name,{"countries":all_countries})

def Ajaxcall(request):
    if request.method == "POST":
        print("hello from ajax")
        country_id = request.POST.get('value')
        cid = country_id.encode('ascii', 'ignore')

        cities=City.objects.filter(country__id=cid[1]).order_by('name').values('name','pk')
        print cities
        str1 = []
        for city in cities:
            currentcity = city['name']
            currentcityint = city['pk']
            currentcitypk = str(currentcityint)
            str1.append("<option name = \'" + currentcity + "\' value = \'" + currentcitypk + '\'' + "> " + currentcity +"</option>")

        print(str1)

        data = str1

        return HttpResponse(data)


def Ajaxcall_district(request):
    if request.method == "POST":
        print("hello from ajax_District")
        city_id = request.POST.get('value')
        cid = city_id.encode('ascii', 'ignore')
        cint = int(cid[1])


        Districts=District.objects.filter(city__id=cint).order_by('name').values('name')
        print Districts
        str2 = []
        for Dis in Districts:
            currentdistrict = Dis['name']
            str2.append("<option name = \'" + currentdistrict + "\' value = \'" + currentdistrict + '\'' + "> " + currentdistrict +"</option>")

        print(str2)

        response2 = str2

        return HttpResponse(response2)

def Ajaxcallcountry(request):
    if request.method == "POST":
        country_name = request.POST.get('value')
        country_n = country_name.encode('ascii', 'ignore')
        c_n = country_n[1:]
        finalc = c_n.replace('"',"")
        finalc_str = str(finalc)

        #finalc = ("%s" %(repr(country_n)[1:-1]))


        print(country_name)




        str3 = []
        if(country_name == u'""'):

            print("nothing")
            result= []

        else:
            result = Country.objects.filter(name__contains=finalc_str).values('name')
        for r in result:
            r1 = r['name'].encode('ascii', 'ignore')


            str3.append("<li>" + r1 + "</li>")
        print(str3)


        return HttpResponse(str3)

countries/templates/file.html
<html>
<head>

<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.2.1.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-3-typeahead/4.0.2/bootstrap3-typeahead.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />

</head>

<body>

<form class="contry-form" action ="#"  method="POST"  id="form">

  {% csrf_token %}
  <select name = "dropdown" id = "dropdown">
    {% for country in countries %}
      <option value ={{ country.pk }} > {{ country.name }}</option>


    {% endfor %}
  </select>

  <select name = "dropdown1" id = "dropdown1">


  </select>

  <select name = "dropdown2" id = "dropdown2">


  </select>

  <div class="container" style="width:600px;">
  <h2 align="center">Autocomplete Textbox using Bootstrap Typeahead with Ajax Django</h2>
  <br /><br />
  <label>Search Country</label>
  <input type="text" name="country" id="country" class="form-control input-lg" autocomplete="off" placeholder="Type Country Name" />
  <div id="countryList"></div>
 </div>


</form>
</body>




<script type="text/javascript">
   $(document).ready(function(){



     $( "#dropdown" ).change(function() {
        var value = $(this).val()
        var token = '{{csrf_token}}';
        $.ajax({
                 headers: { "X-CSRFToken": token },
                  type: "POST",
                  url: "{% url 'countries:Ajaxcall' %}",

                  data: {
                    'value': JSON.stringify(value)
                  },


                  success: function(data){
                    dataType : 'html'
                    console.log("success test")
                    console.log(data)

                    $('#dropdown1').empty().append(data);
                  }
              });

       });


       $( "#dropdown1" ).change(function() {
          var value = $(this).val()
          var token = '{{csrf_token}}';
          $.ajax({
                   headers: { "X-CSRFToken": token },
                    type: "POST",
                    url: "{% url 'countries:Ajaxcall_district' %}",

                    data: {
                      'value': JSON.stringify(value)
                    },


                    success: function(response2){
                      dataType : 'html'
                      console.log("success test")
                      console.log(response2)

                      $('#dropdown2').empty().append(response2);

                    }
                });

         });

  $('#country').keyup(function(query){
    var token = '{{csrf_token}}';
    var query = $(this).val()


  $.ajax({
  headers: { "X-CSRFToken": token },
  type: "POST",
   url: "{% url 'countries:Ajaxcallcountry' %}",

   data: {
     'value': JSON.stringify(query)
   },
   success:function(data)
    {
      
      $('#countryList').fadeIn();
      $('#countryList').html(data);
     }

  })

});
$(document).on('click', 'li', function(){
         $('#country').val($(this).text());
         $('#countryList').fadeOut();
    });



})
</script>
</html>